# Brain Stroke Prediction
## (Logistic Regression)

In [1]:
import numpy as np
import pandas as pd


In [2]:
data=pd.read_csv(r"C:\Users\Parimal\Downloads\Brain Stroke.csv")
data

gender   age  hypertension  heart_disease ever_married      work_type  \
0       Male  67.0             0              1          Yes        Private   
1       Male  80.0             0              1          Yes        Private   
2     Female  49.0             0              0          Yes        Private   
3     Female  79.0             1              0          Yes  Self-employed   
4       Male  81.0             0              0          Yes        Private   
...      ...   ...           ...            ...          ...            ...   
4976    Male  41.0             0              0           No        Private   
4977    Male  40.0             0              0          Yes        Private   
4978  Female  45.0             1              0          Yes       Govt_job   
4979    Male  40.0             0              0          Yes        Private   
4980  Female  80.0             1              0          Yes        Private   

     Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
0             Urban             228.69  36.6  formerly smoked       1  
1             Rural             105.92  32.5     never smoked       1  
2             Urban             171.23  34.4           smokes       1  
3             Rural             174.12  24.0     never smoked       1  
4             Urban             186.21  29.0  formerly smoked       1  
...             ...                ...   ...              ...     ...  
4976          Rural              70.15  29.8  formerly smoked       0  
4977          Urban             191.15  31.1           smokes       0  
4978          Rural              95.02  31.8           smokes       0  
4979          Rural              83.94  30.0           smokes       0  
4980          Urban              83.75  29.1     never smoked       0  

[4981 rows x 11 columns]

In [3]:
data["stroke"].value_counts()

0    4733
1     248
Name: stroke, dtype: int64

In [4]:
data.isnull().any()

gender               False
age                  False
hypertension         False
heart_disease        False
ever_married         False
work_type            False
Residence_type       False
avg_glucose_level    False
bmi                  False
smoking_status       False
stroke               False
dtype: bool

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4981 entries, 0 to 4980
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   gender             4981 non-null   object 
 1   age                4981 non-null   float64
 2   hypertension       4981 non-null   int64  
 3   heart_disease      4981 non-null   int64  
 4   ever_married       4981 non-null   object 
 5   work_type          4981 non-null   object 
 6   Residence_type     4981 non-null   object 
 7   avg_glucose_level  4981 non-null   float64
 8   bmi                4981 non-null   float64
 9   smoking_status     4981 non-null   object 
 10  stroke             4981 non-null   int64  
dtypes: float64(3), int64(3), object(5)
memory usage: 428.2+ KB


# LabelEncoding

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
LE=LabelEncoder()

In [8]:
col=["gender","ever_married","work_type","Residence_type","smoking_status"]

In [9]:
data[col]=LE.fit_transform(col)

In [10]:
data

gender   age  hypertension  heart_disease  ever_married  work_type  \
0          2  67.0             0              1             1          4   
1          2  80.0             0              1             1          4   
2          2  49.0             0              0             1          4   
3          2  79.0             1              0             1          4   
4          2  81.0             0              0             1          4   
...      ...   ...           ...            ...           ...        ...   
4976       2  41.0             0              0             1          4   
4977       2  40.0             0              0             1          4   
4978       2  45.0             1              0             1          4   
4979       2  40.0             0              0             1          4   
4980       2  80.0             1              0             1          4   

      Residence_type  avg_glucose_level   bmi  smoking_status  stroke  
0                  0             228.69  36.6               3       1  
1                  0             105.92  32.5               3       1  
2                  0             171.23  34.4               3       1  
3                  0             174.12  24.0               3       1  
4                  0             186.21  29.0               3       1  
...              ...                ...   ...             ...     ...  
4976               0              70.15  29.8               3       0  
4977               0             191.15  31.1               3       0  
4978               0              95.02  31.8               3       0  
4979               0              83.94  30.0               3       0  
4980               0              83.75  29.1               3       0  

[4981 rows x 11 columns]

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4981 entries, 0 to 4980
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   gender             4981 non-null   int64  
 1   age                4981 non-null   float64
 2   hypertension       4981 non-null   int64  
 3   heart_disease      4981 non-null   int64  
 4   ever_married       4981 non-null   int64  
 5   work_type          4981 non-null   int64  
 6   Residence_type     4981 non-null   int64  
 7   avg_glucose_level  4981 non-null   float64
 8   bmi                4981 non-null   float64
 9   smoking_status     4981 non-null   int64  
 10  stroke             4981 non-null   int64  
dtypes: float64(3), int64(8)
memory usage: 428.2 KB


# Data Imbalancing

In [12]:
data["stroke"].value_counts()

0    4733
1     248
Name: stroke, dtype: int64

In [13]:
x=data.iloc[:,:-1]
x


gender   age  hypertension  heart_disease  ever_married  work_type  \
0          2  67.0             0              1             1          4   
1          2  80.0             0              1             1          4   
2          2  49.0             0              0             1          4   
3          2  79.0             1              0             1          4   
4          2  81.0             0              0             1          4   
...      ...   ...           ...            ...           ...        ...   
4976       2  41.0             0              0             1          4   
4977       2  40.0             0              0             1          4   
4978       2  45.0             1              0             1          4   
4979       2  40.0             0              0             1          4   
4980       2  80.0             1              0             1          4   

      Residence_type  avg_glucose_level   bmi  smoking_status  
0                  0             228.69  36.6               3  
1                  0             105.92  32.5               3  
2                  0             171.23  34.4               3  
3                  0             174.12  24.0               3  
4                  0             186.21  29.0               3  
...              ...                ...   ...             ...  
4976               0              70.15  29.8               3  
4977               0             191.15  31.1               3  
4978               0              95.02  31.8               3  
4979               0              83.94  30.0               3  
4980               0              83.75  29.1               3  

[4981 rows x 10 columns]

In [14]:
y=data.iloc[:,-1]
y

0       1
1       1
2       1
3       1
4       1
       ..
4976    0
4977    0
4978    0
4979    0
4980    0
Name: stroke, Length: 4981, dtype: int64

### CASE :01 (Under Sampling)

In [15]:
from imblearn.under_sampling  import RandomUnderSampler

In [16]:
under_sample=RandomUnderSampler()

In [17]:
x_under,y_under=under_sample.fit_resample(x,y)


In [18]:
x_under

gender   age  hypertension  heart_disease  ever_married  work_type  \
0         2  31.0             0              0             1          4   
1         2  52.0             0              0             1          4   
2         2  10.0             0              0             1          4   
3         2  71.0             0              0             1          4   
4         2  43.0             0              0             1          4   
..      ...   ...           ...            ...           ...        ...   
491       2  79.0             0              0             1          4   
492       2  74.0             0              0             1          4   
493       2  76.0             1              1             1          4   
494       2  74.0             0              0             1          4   
495       2  71.0             1              0             1          4   

     Residence_type  avg_glucose_level   bmi  smoking_status  
0                 0              70.65  29.9               3  
1                 0             126.68  28.1               3  
2                 0              63.08  20.5               3  
3                 0              93.28  34.7               3  
4                 0             101.75  26.7               3  
..              ...                ...   ...             ...  
491               0             114.77  27.2               3  
492               0             167.13  28.7               3  
493               0             199.86  31.7               3  
494               0              60.98  28.1               3  
495               0              87.80  30.8               3  

[496 rows x 10 columns]

In [19]:
x_under.count()

gender               496
age                  496
hypertension         496
heart_disease        496
ever_married         496
work_type            496
Residence_type       496
avg_glucose_level    496
bmi                  496
smoking_status       496
dtype: int64

In [20]:
y_under.count()

496

#  Spliting data
### (Cross Validation -> K-Fold)

In [21]:
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from numpy import mean
from numpy import absolute

In [22]:
cv = KFold(n_splits=10, random_state=10, shuffle=True)

In [23]:
cv

KFold(n_splits=10, random_state=10, shuffle=True)

In [24]:
model=LogisticRegression()

In [25]:
scores=cross_val_score(model,x_under,y_under,cv=cv)

C:\Users\Parimal\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Parimal\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_i

In [26]:
scores

array([0.76      , 0.72      , 0.74      , 0.76      , 0.74      ,
       0.78      , 0.79591837, 0.7755102 , 0.65306122, 0.75510204])

# Accuracy

In [52]:
u_accuracy=mean(scores)
u_accuracy

0.7672729728462644

### CASE :02 (Over Sampling)

In [28]:
from imblearn.over_sampling import RandomOverSampler

In [29]:
over_sample=RandomOverSampler()

In [30]:
x_over, y_over =over_sample.fit_resample(x,y)

In [37]:
x_over.shape

(9466, 10)

In [39]:
y_over.shape

(9466,)

#  Spliting data
### (Cross Validation -> K-Fold)

In [45]:
cv=KFold(n_splits=10,random_state=10,shuffle=True)

In [47]:
scores=cross_val_score(model,x_over,y_over,cv=cv)

In [49]:
scores

array([0.77296727, 0.75818374, 0.77930306, 0.7592397 , 0.77085533,
       0.75712777, 0.77272727, 0.74841438, 0.76004228, 0.79386892])

# Accuracy

In [53]:
o_accuracy=mean(scores)
o_accuracy

0.7672729728462644

### CASE :03 (SMOTE)

In [59]:
from  imblearn.over_sampling  import SMOTE

In [61]:
smote=SMOTE()

In [62]:
x_smote,y_smote=smote.fit_resample(x,y)

In [63]:
print(x_smote.shape,y_smote.shape)

(9466, 10) (9466,)


#  Spliting data
### (Cross Validation -> K-Fold)

In [64]:
cv=KFold(n_splits=10,random_state=10,shuffle=True)

In [66]:
scores=cross_val_score(model,x_smote,y_smote,cv=cv)
scores

array([0.78563886, 0.7719113 , 0.76979937, 0.7592397 , 0.78035903,
       0.76451954, 0.77484144, 0.75475687, 0.78224101, 0.78646934])

In [67]:
s_accuracy=mean(scores)
s_accuracy

0.7729776461106733

# Results

In [69]:
print("......................................................................")
print("Accuracy Score of LRM with Under sampling tech. is :",u_accuracy)
print("Accuracy Score of LRM with over sampling tech. is :",o_accuracy)
print("Accuracy Score of LRM with SMOTE sampling tech. is :",s_accuracy)
print("......................................................................")

......................................................................
Accuracy Score of LRM with Under sampling tech. is : 0.7672729728462644
Accuracy Score of LRM with over sampling tech. is : 0.7672729728462644
Accuracy Score of LRM with SMOTE sampling tech. is : 0.7729776461106733
......................................................................
